### ISSUE TITLE
Compatibility with NetBeans annotation processors.

### ISSUE THREAD

**Issue by marat-gainullin** [radimk/gradle-nbm-plugin#12]
Annotation processors check resources existance while compilation. Unfortunately, they can't locate resources in standard gradle project layout and `compileJava`task fails if a project has annotations wich mention some resources, such as icons or localization bundles.

**Comment by radimk** [comment]
Do you have a sample project showing this problem?

**Comment by marat-gainullin** [comment]
The pull request contains standalone sample edited so, thart `compileJava` task fails to process it agains NetBeans' annotation processors.

**Comment by marat-gainullin** [comment]
The following snippet fixes the problem:
```
compileJava {
    options.compilerArgs = ['-sourcepath', "$project.projectDir/src/main/resources"]
}
```
