### ISSUE TITLE
It does not appear possible to use the maven-publish plugin to publish an module.

### ISSUE THREAD

**Issue by Richard-Cranium** [radimk/gradle-nbm-plugin#15]
If you can tell me how to do so, I'll close this issue in a heartbeat.

Every time that I've tried it, I get a...
Cannot configure the 'publishing' extension after it has been accessed.
...error message.

**Comment by radimk** [comment]
Can you add a simple example of your build script?

**Comment by Richard-Cranium** [comment]
It is possible, but it's not as simple as one would like.

The nbm extension block must come before the publishing extension block in build.gradle.

In the case of my build.groovy, it looks like this:
```groovy
nbm {
    moduleName="cx.ath.matthew.unix"
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			groupId "net.verizon.mflacy"
			version project.version
			artifact tasks.nbm.outputFile
		}
	}
	repositories {
		maven {
			url "${artifactRepoBase}/${project.version.endsWith('-SNAPSHOT') ? 'maven-snapshots' : 'maven-releases'}"
			credentials {
				username nexusUsername
				password nexusPassword
			}
		}
	}
}
```
*artifactRepoBase* is set in an ext {} block and points to my private nexus server.  *nexusUsername* and *nexusPassword* are set in my ~/.gradle/gradle.properties file.

The above configuration **did** push the module up to my server, so I'm going to close this.  Sorry for the noise.

**Comment by Richard-Cranium** [comment]
After digging around in this for a while, the above "works" in that the nbm file is pushed to the nexus repository.

However, Netbeans expects to also see the jar file found in the nbm with the exact same name (for snapshot versions) as the nbm.

So, the way to fix that is to change the publishing block slightly (it still must be after the nbm extentiion block)...
```
publishing {
	publications {
		jar(MavenPublication) {
			groupId "net.verizon.mflacy"
			artifactId nbm.moduleName.replace('.','-')
			version project.version
			artifact file("${tasks.netbeans.moduleBuildDir}/modules/${nbm.moduleName.replace('.','-')}.jar")
			
			artifact tasks.nbm.outputFile
		}
	}
	repositories {
		maven {
			url "${artifactRepoBase}/${project.version.endsWith('-SNAPSHOT') ? 'maven-snapshots' : 'maven-releases'}"
			credentials {
				username nexusUsername
				password nexusPassword
			}
		}
	}
}
```
