### ISSUE TITLE
Plugin is not compatible with Gradle's nightly (3.4)

### ISSUE THREAD

**Issue by kelemen** [radimk/gradle-nbm-plugin#22]
When using Gradle's nightly build, applying the plugin yields the following error:

> Failed to apply plugin [id 'cz.kubacki.nbm']
   > Cannot add a configuration with name 'implementation' as a configuration with that name already exists.

**Comment by radimk** [comment]
looks like a large change in Gradle is brewing - https://github.com/gradle/gradle/commit/0d442a55b445f537efbce65267ce9418fce2e7a8#diff-83f0eaa4ff604af6ab3b1bcc44250720R59

I'll rename the configuration.

**Comment by radimk** [comment]
1.16.0 is out (probably I should have called it 1.15.1 but it is already done)
