### ISSUE TITLE
double star package export in manifest broken

### ISSUE THREAD

**Issue by guai** [radimk/gradle-nbm-plugin#23]
As I can see, this code adds a star now, but I see no way it can produce double star
```
private static String toStarImport(String packageName) {
    String suffix = ".*";
    return packageName.endsWith(suffix)
            ? packageName
            : packageName + suffix;
}
```
given `foobar.**` becomes `foobar.**.*`
given `foobar.*` stays
givan `foobar` becomes `foobar.*`

**Comment by radimk** [comment]
Well, can you submit a PR to fix this?

**Comment by guai** [comment]
[I did](https://github.com/radimk/gradle-nbm-plugin/pull/24)
