### ISSUE TITLE
What's the task to build module?

### ISSUE THREAD

**Issue by SerVB** [radimk/gradle-nbm-plugin#34]
The README says the "release" task builds the module but Gradle says such a task doesn't exist.

Am I right that to build a module the "netbeans" should be executed?

**Comment by radimk** [comment]
https://github.com/radimk/gradle-nbm-plugin#development-notes is about building the plugin itself and making its release.
Check Gertjaan's tutorial to find how to use the plugin.

**Comment by SerVB** [comment]
I try to use this "release" task from development notes, as I've said... It doesn't work.

Reading the tutorial doesn't help: there is no guide "how to build the module file that can be published to NetBeans Plugins Portal".

**Comment by SerVB** [comment]
@radimk, could you reopen this or answer please?

The issue here that `Task 'release' not found`.
