### ISSUE TITLE
Could not get unknown property 'classesDir' error when using Gradle 5 or later

### ISSUE THREAD

**Issue by hajdam** [radimk/gradle-nbm-plugin#36]
Hi, when using gradle-nbm-plugin:1.17.0 from jcenter I get following error when using Gradle 5 or later (tested with 5.2.1, 6.5.1) on Linux 64bit with JDK 8, 11 or 14:

```
Execution failed for task ':compileJava'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
```
So either I have to use Gradle 4.x and JDK8 or as a workaround I compiled plugin myself with Gradle 4.6, JDK 8 and it works for now, but I have to include it as a binary library which is not ideal.

My guess is, that version 1.17.0 was compiled with even older JDK/Gradle and this might be causing the issue.
Could it be possible to deploy new version of the plugin compiled with more recent Gradle version?

Used in projects:
https://github.com/exbin/bined-netbeans-plugin
https://github.com/hajdam/guipopup-netbeans-plugin

And btw. thank you for the plugin!

**Comment by radimk** [comment]
Indeed, it was compiled a while ago. Removal of `classesDir` is mentioned in migration guide https://docs.gradle.org/current/userguide/upgrading_version_4.html as one of incompatible changes.
A patch with the fix would be nice. Some fork(s) can even have it. It would definitely make it more likely that I'd deal with the problem. Because I am not really using this anymore.

**Comment by hajdam** [comment]
What I was trying to say is, that no change to source code seems to be necessary. Just build plugin using Gradle 4.x (or later) and publish.

At least that is what worked for me. I can test/check if your build will work for my case or I'll try to provide any further assistance, if needed.

(I think either 'classesDir' was already renamed to 'classesDirs' in previous commits or it was generated in 1.17.0 version due to use of older Gradle for plugin build)

**Comment by hajdam** [comment]
Included build of more recent version of the plugin. Hopefully it works now.
