### ISSUE TITLE
Multimodule sample

### ISSUE THREAD

**Issue by guai** [radimk/gradle-nbm-plugin#4]
Hi. I've pushed my projects's build script into my fork here https://github.com/guai/gradle-nbm-plugin/blob/master/samples/multimodule/build.gradle
My project have multiple netbeans modules
It also have slightly different netbeans launching task with all the subprojects as clusters. And I've also added code that patches Intellij IDEA's project and adds configuration for launching netbeans from inside IDEA
Maybe you are interested in incorporation this stuff into plugin...

**Comment by radimk** [comment]
sorry that this is taking too long. I'm going to look at this next week when I am back from travels.

**Comment by radimk** [comment]
I linked your code from https://github.com/radimk/gradle-nbm-plugin/wiki/FAQ and hope that there will be more complete example provided by Atila Kelemen in the future. Thanks and sorry that this slipped through the cracks.
