### ISSUE TITLE
Allow setting the location of a modules layer xml

### ISSUE THREAD

**Issue by mklaehn** [radimk/gradle-nbm-plugin#8]
this allows working around issue of the Todo "fix resource lookup when running annotation processors"

**Comment by radimk** [comment]
I am OK to merge this. Before doing this I'd like to clarify: you use it to generate layer file manually instead of relying on generated layer.xml that would register services annotated in sources?

**Comment by radimk** [comment]
no response makes me uncertain about merging this.

**Comment by mklaehn** [comment]
I had some other commitments. Sorry.

Yes, I've encountered problems with the TemplateRegistration annotation as it is searching for referenced resources. So I've wanted to place a layer.xml file the way I manually can with NetBeans modules and had no way to register the file.
Auto-generated layer files - as in generated-lay.xml - is an easy way to register "stuff" in the layer filesystem but by no means the only way. So registering a custom layer file has to possible.

**Comment by radimk** [comment]
Looking again at this patch I think it is not adding too much value: you can always add `OpenIDE-Module-Layer: path/to/your/layer.xml` line to `src/main/nbm/manifest.mf`. That file is merged with generated manifest and it works.
I understand that it can be common to have custom layer file and there is temptation to specify it in build DSL. But there is also few other things that make it unrealistic to expect that everything will be declared in buildscript.
Do you really consider it so important change?

**Comment by mklaehn** [comment]
I was not aware that `src/main/nbm/manifest.mf` is merged with the generated manifest. So if that works this issues more or less becomes moot.
